export const availableCards: string[] = [
    "bell", "bell",
    "kiss", "kiss",
    "lightbulb", "lightbulb",
    "lotus", "lotus",
    "magnet", "magnet",
    "money", "money",
    "owl", "owl",
    "rain", "rain",
    "salaryman", "salaryman",
    "schoolgirl", "schoolgirl",
    "ship", "ship",
    "soccer", "soccer",
    "squirrel", "squirrel",
    "strength", "strength",
    "sun", "sun",
    "sunset", "sunset",
    "superhero", "superhero",
    "swimming", "swimming",
    "thanks", "thanks",
    "tree", "tree"
  ];